window.esdocSearchIndex = [
  [
    "aureooms-js-cardinality/src/1-sugar.js~at_least",
    "variable/index.html#static-variable-at_least",
    "<span>at_least</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/1-sugar.js</span>",
    "variable"
  ],
  [
    "aureooms-js-cardinality/src/1-sugar.js~at_most",
    "variable/index.html#static-variable-at_most",
    "<span>at_most</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/1-sugar.js</span>",
    "variable"
  ],
  [
    "aureooms-js-cardinality/src/1-sugar.js~between",
    "variable/index.html#static-variable-between",
    "<span>between</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/1-sugar.js</span>",
    "variable"
  ],
  [
    "aureooms-js-cardinality/src/1-sugar.js~count",
    "variable/index.html#static-variable-count",
    "<span>count</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/1-sugar.js</span>",
    "variable"
  ],
  [
    "aureooms-js-cardinality/src/1-sugar.js~empty",
    "variable/index.html#static-variable-empty",
    "<span>empty</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/1-sugar.js</span>",
    "variable"
  ],
  [
    "aureooms-js-cardinality/src/0-core/eq.js~eq",
    "function/index.html#static-function-eq",
    "<span>eq</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/eq.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/ge.js~ge",
    "function/index.html#static-function-ge",
    "<span>ge</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/ge.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/gele.js~gele",
    "function/index.html#static-function-gele",
    "<span>gele</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/gele.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/gelt.js~gelt",
    "function/index.html#static-function-gelt",
    "<span>gelt</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/gelt.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/gt.js~gt",
    "function/index.html#static-function-gt",
    "<span>gt</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/gt.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/gtle.js~gtle",
    "function/index.html#static-function-gtle",
    "<span>gtle</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/gtle.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/gtlt.js~gtlt",
    "function/index.html#static-function-gtlt",
    "<span>gtlt</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/gtlt.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/le.js~le",
    "function/index.html#static-function-le",
    "<span>le</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/le.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/len.js~len",
    "function/index.html#static-function-len",
    "<span>len</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/len.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/lt.js~lt",
    "function/index.html#static-function-lt",
    "<span>lt</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/lt.js</span>",
    "function"
  ],
  [
    "aureooms-js-cardinality/src/0-core/ne.js~ne",
    "function/index.html#static-function-ne",
    "<span>ne</span> <span class=\"search-result-import-path\">aureooms-js-cardinality/src/0-core/ne.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/0-core/eq.js",
    "file/src/0-core/eq.js.html",
    "src/0-core/eq.js",
    "file"
  ],
  [
    "src/0-core/ge.js",
    "file/src/0-core/ge.js.html",
    "src/0-core/ge.js",
    "file"
  ],
  [
    "src/0-core/gele.js",
    "file/src/0-core/gele.js.html",
    "src/0-core/gele.js",
    "file"
  ],
  [
    "src/0-core/gelt.js",
    "file/src/0-core/gelt.js.html",
    "src/0-core/gelt.js",
    "file"
  ],
  [
    "src/0-core/gt.js",
    "file/src/0-core/gt.js.html",
    "src/0-core/gt.js",
    "file"
  ],
  [
    "src/0-core/gtle.js",
    "file/src/0-core/gtle.js.html",
    "src/0-core/gtle.js",
    "file"
  ],
  [
    "src/0-core/gtlt.js",
    "file/src/0-core/gtlt.js.html",
    "src/0-core/gtlt.js",
    "file"
  ],
  [
    "src/0-core/le.js",
    "file/src/0-core/le.js.html",
    "src/0-core/le.js",
    "file"
  ],
  [
    "src/0-core/len.js",
    "file/src/0-core/len.js.html",
    "src/0-core/len.js",
    "file"
  ],
  [
    "src/0-core/lt.js",
    "file/src/0-core/lt.js.html",
    "src/0-core/lt.js",
    "file"
  ],
  [
    "src/0-core/ne.js",
    "file/src/0-core/ne.js.html",
    "src/0-core/ne.js",
    "file"
  ],
  [
    "src/1-sugar.js",
    "file/src/1-sugar.js.html",
    "src/1-sugar.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]